import uuid
from typing import List, Dict

try:
    from ..db import SessionLocal
    from ..schemas.guidance import DiseaseGuidance
except ImportError:
    from db import SessionLocal
    from schemas.guidance import DiseaseGuidance


SEED_DATA: List[Dict[str, str]] = [
    # Wheat
    {
        'crop': 'wheat',
        'name': 'Aphid',
        'type': 'Insect pest',
        'symptoms': 'Curling of leaves; honeydew; sooty mould',
        'cultural_controls': 'Encourage natural enemies (ladybird beetles); remove weed hosts; balanced nitrogen; avoid unnecessary sprays',
        'chemical_control': 'Neonicotinoids (imidacloprid, thiamethoxam); pyrethroids (lambda-cyhalothrin)',
        'brands': 'Confidor (Imidacloprid) — Bayer; Actara (Thiamethoxam) — Syngenta; Karate (Lambda-cyhalothrin) — Syngenta',
        'notes': 'Follow label; prefer spot treatment; promote coccinellids',
    },
    {
        'crop': 'wheat', 'name': 'Mite', 'type': 'Insect pest',
        'symptoms': 'Yellowing; stippling of leaves',
        'cultural_controls': 'Avoid drought stress; remove alternate hosts; use predatory mites where available',
        'chemical_control': 'Acaricides: propargite; dicofol; abamectin',
        'brands': 'Abamectin formulations available from local agroshops',
        'notes': 'Rotate modes of action to avoid resistance',
    },
    {
        'crop': 'wheat', 'name': 'Stem fly', 'type': 'Insect pest',
        'symptoms': 'White earheads; dead tillers',
        'cultural_controls': 'Timely sowing; destroy volunteer cereals; plough residues',
        'chemical_control': 'Seed treatments/systemic insecticides: imidacloprid; thiamethoxam',
        'brands': 'Confidor; Actara',
        'notes': 'Seed treat at recommended dose',
    },
    {
        'crop': 'wheat', 'name': 'Wheat Coccin (ladybird)', 'type': 'Beneficial insect',
        'symptoms': 'Predator of aphids',
        'cultural_controls': 'Conserve by avoiding broad-spectrum insecticides',
        'chemical_control': 'No chemical control (beneficial)',
        'brands': '—',
        'notes': 'Avoid spraying when beneficials present',
    },
    {
        'crop': 'wheat', 'name': 'Black Rust (Stem rust)', 'type': 'Fungal disease',
        'symptoms': 'Reddish/brown pustules on stems and leaves',
        'cultural_controls': 'Resistant cultivars; timely sowing; remove volunteer hosts; seed treatment',
        'chemical_control': 'Triazoles (propiconazole; tebuconazole)',
        'brands': 'Tilt (Propiconazole)',
        'notes': 'Use resistant varieties; monitor races',
    },
    {
        'crop': 'wheat', 'name': 'Brown Rust (Leaf rust)', 'type': 'Fungal disease',
        'symptoms': 'Orange-brown pustules on leaves',
        'cultural_controls': 'Resistant varieties; balanced nutrition; remove volunteer wheat',
        'chemical_control': 'Triazoles (propiconazole); QoI (azoxystrobin)',
        'brands': 'Tilt; Amistar (mixtures)',
        'notes': 'Spray at early onset; rotate chemistries',
    },
    {
        'crop': 'wheat', 'name': 'Yellow Rust (Stripe rust)', 'type': 'Fungal disease',
        'symptoms': 'Yellow stripes of pustules on leaves',
        'cultural_controls': 'Resistant varieties; avoid late irrigation; spray at first signs',
        'chemical_control': 'Propiconazole; tebuconazole; azoxystrobin',
        'brands': 'Tilt; Amistar Top (azoxystrobin + difenoconazole)',
        'notes': 'Monitor fields regularly',
    },
    {
        'crop': 'wheat', 'name': 'Black point', 'type': 'Physiological/fungal complex',
        'symptoms': 'Darkening at embryo end of grain',
        'cultural_controls': 'Avoid excessive humidity during grain filling; timely harvest; good drying',
        'chemical_control': 'No specific fungicide; manage pre-harvest conditions',
        'brands': '—',
        'notes': 'Mostly cultural control',
    },
    {
        'crop': 'wheat', 'name': 'Common root rot', 'type': 'Fungal disease',
        'symptoms': 'Root and crown browning; poor tillering',
        'cultural_controls': 'Crop rotation; deep ploughing; seed treatment',
        'chemical_control': 'Seed treatment: metalaxyl + mancozeb; thiram',
        'brands': 'Metalaxyl + mancozeb combos in Pakistan',
        'notes': 'Use certified seed',
    },
    {
        'crop': 'wheat', 'name': 'Head blast', 'type': 'Fungal disease',
        'symptoms': 'Bleached/premature ripening of spikes',
        'cultural_controls': 'Resistant varieties; avoid high N at heading; spray at heading',
        'chemical_control': 'Triazoles; strobilurins',
        'brands': 'Amistar Top; Tilt',
        'notes': 'Risk of mycotoxins — consult extension',
    },
    {
        'crop': 'wheat', 'name': 'Fusarium Head Blight (Scab)', 'type': 'Fungal disease',
        'symptoms': 'Bleached spikelets; pinkish fungal growth; mycotoxin contamination',
        'cultural_controls': 'Rotate away from maize; deep plough residues; tolerant varieties; seed treatment',
        'chemical_control': 'Prophylactic at flowering: tebuconazole; azoxystrobin mixes',
        'brands': 'Amistar Top; tebuconazole products',
        'notes': 'Do not feed contaminated grain; follow PHI',
    },
    {
        'crop': 'wheat', 'name': 'Fusarium Foot Rot', 'type': 'Fungal disease',
        'symptoms': 'Dark discoloration of crown/foot; stunting',
        'cultural_controls': 'Rotation; avoid waterlogging; seed treatments',
        'chemical_control': 'Carbendazim; metalaxyl + mancozeb (seed)',
        'brands': 'Bavistin; Mancozeb combos',
        'notes': 'Manage residues; healthy seed',
    },
    {
        'crop': 'wheat', 'name': 'Leaf Blight (Spot blotch)', 'type': 'Fungal disease',
        'symptoms': 'Dark brown spots on leaves; coalescing',
        'cultural_controls': 'Tolerant varieties; balanced N; timely spray',
        'chemical_control': 'Carbendazim; propiconazole; mancozeb',
        'brands': 'Bavistin; Tilt; Dithane',
        'notes': 'Spray early; rotate chemistry',
    },
    {
        'crop': 'wheat', 'name': 'Leaf blast', 'type': 'Fungal disease',
        'symptoms': 'Elliptical lesions on leaves; similar to rice blast',
        'cultural_controls': 'Resistant cultivars; avoid excessive N; manage water',
        'chemical_control': 'Propiconazole; azoxystrobin',
        'brands': 'Tilt; Amistar Top',
        'notes': 'Monitor and spray early',
    },
    {
        'crop': 'wheat', 'name': 'Spot Blotch(Sep)', 'type': 'Fungal disease',
        'symptoms': 'Irregular dark brown lesions; coalescing blight on leaves',
        'cultural_controls': 'Use tolerant varieties; rotate crops; avoid excess nitrogen; remove crop debris',
        'chemical_control': 'Propiconazole or tebuconazole at first signs; mancozeb for protection',
        'brands': 'Tilt (Propiconazole); Dithane (Mancozeb)',
        'notes': 'Spray early and rotate fungicide modes of action',
    },
    {
        'crop': 'wheat', 'name': 'Powdery mildew', 'type': 'Fungal disease',
        'symptoms': 'White powdery growth on leaf surface',
        'cultural_controls': 'Resistant varieties; avoid dense canopy; sulfur dusting',
        'chemical_control': 'Sulfur; propiconazole',
        'brands': 'Sulfur formulations; Tilt',
        'notes': 'Cultural preferred; sulfur low-cost',
    },
    {
        'crop': 'wheat', 'name': 'Septoria (Zymoseptoria)', 'type': 'Fungal disease',
        'symptoms': 'Irregular brown lesions with black pycnidia',
        'cultural_controls': 'Rotation; residue management; resistant varieties',
        'chemical_control': 'Azoxystrobin; propiconazole; carbendazim',
        'brands': 'Amistar Top; Tilt; Bavistin',
        'notes': 'Rotate fungicide families',
    },
    {
        'crop': 'wheat', 'name': 'Smut', 'type': 'Fungal disease',
        'symptoms': 'Kernels replaced by dark smut sori; rotten smell',
        'cultural_controls': 'Certified seed; hot water seed treatment; resistant varieties',
        'chemical_control': 'Seed treatment: carboxin; thiram',
        'brands': 'Local seed treatment products',
        'notes': 'Seed sanitation is key',
    },
    {
        'crop': 'wheat', 'name': 'Tan spot', 'type': 'Fungal disease',
        'symptoms': 'Tan necrotic spots with yellow halo',
        'cultural_controls': 'Residue management; crop rotation; tolerant varieties',
        'chemical_control': 'Triazoles; mancozeb',
        'brands': 'Tilt; Dithane',
        'notes': 'Integrated approach best',
    },
    {
        'crop': 'wheat', 'name': 'Wheat Scab', 'type': 'Fungal disease',
        'symptoms': 'Same as Fusarium Head Blight',
        'cultural_controls': 'See FHB entry',
        'chemical_control': 'See FHB',
        'brands': 'See FHB',
        'notes': 'Same notes',
    },

    # Rice
    {'crop': 'rice', 'name': 'Brown Plant Hopper', 'type': 'Insect pest',
     'symptoms': 'Yellowing; hopper burn; plant death',
     'cultural_controls': 'Resistant varieties; balanced nitrogen; maintain water level; release parasitoids/predators; sticky traps',
     'chemical_control': 'Neonicotinoids (imidacloprid; thiamethoxam); pymetrozine',
     'brands': 'Confidor; Actara; check local labels',
     'notes': 'Avoid blanket sprays; IPM and thresholds'},
    {'crop': 'rice', 'name': 'Rice Leaf Hopper', 'type': 'Insect pest',
     'symptoms': 'Stunted plants; yellowing; tungro transmission',
     'cultural_controls': 'Resistant varieties; remove grassy weeds; conserve predators',
     'chemical_control': 'Thiamethoxam; imidacloprid; pyrethroids',
     'brands': 'Actara; Confidor; Karate',
     'notes': 'Vector control reduces spread'},
    {'crop': 'rice', 'name': 'Rice Leaf Roller', 'type': 'Insect pest',
     'symptoms': 'Rolled leaves with feeding damage',
     'cultural_controls': 'Clean nursery; release Trichogramma; avoid excessive N',
     'chemical_control': 'Bt products; pyrethroids; spinosad',
     'brands': 'Spinosad and Bt products; carbaryl formulations',
     'notes': 'Follow IPM and thresholds'},
    {'crop': 'rice', 'name': 'Green Leaf Hopper', 'type': 'Insect pest',
     'symptoms': 'Yellowing; tungro transmission',
     'cultural_controls': 'Same as leaf hopper; conserve predators',
     'chemical_control': 'Thiamethoxam; imidacloprid; pymetrozine; pyrethroids',
     'brands': 'Actara; Confidor; pymetrozine products',
     'notes': 'Prefer selective insecticides'},
    {'crop': 'rice', 'name': 'Rice Stem Borer', 'type': 'Insect pest',
     'symptoms': 'Deadheart; whiteheads',
     'cultural_controls': 'Light/pheromone traps; timely transplanting; destroy stubble',
     'chemical_control': 'Cartap hydrochloride; chlorpyrifos (check registration); Bt',
     'brands': 'Bt and cartap products',
     'notes': 'Use trap cropping; sanitation'},
    {'crop': 'rice', 'name': 'Rice Water Weevil', 'type': 'Insect pest',
     'symptoms': 'Stunted plants from root feeding',
     'cultural_controls': 'Avoid continuous flooding; maintain healthy stands',
     'chemical_control': 'Systemic insecticides (neonicotinoids) as needed',
     'brands': 'Confidor; Actara',
     'notes': 'Check rice-specific formulations'},
    {'crop': 'rice', 'name': 'Rice Bug (Leptocorisa)', 'type': 'Insect pest',
     'symptoms': 'Discolored grains; premature ripening',
     'cultural_controls': 'Monitor milky stage; remove infested panicles; hygiene',
     'chemical_control': 'Pyrethroids (lambda-cyhalothrin) or organophosphates (where registered)',
     'brands': 'Karate (lambda-cyhalothrin)',
     'notes': 'Follow label and PHI'},
    {'crop': 'rice', 'name': 'Thrips', 'type': 'Insect pest',
     'symptoms': 'Silvering and scarring of leaves; poor tillering',
     'cultural_controls': 'Avoid water stress; reflective mulches; conserve predators',
     'chemical_control': 'Spinosad; pyrethroids; neonicotinoids',
     'brands': 'Spinosad and pyrethroid formulations',
     'notes': 'Rotate modes of action'},
    {'crop': 'rice', 'name': 'Rice Gall Midge', 'type': 'Insect pest',
     'symptoms': 'Silver shoots (galls); no panicle formation',
     'cultural_controls': 'Resistant varieties; adjust planting dates; rogue early',
     'chemical_control': 'Limited efficacy; early systemic insecticides sometimes used',
     'brands': 'Local options vary',
     'notes': 'Resistant varieties are best'},
    {'crop': 'rice', 'name': 'Bacterial Blight', 'type': 'Bacterial disease',
     'symptoms': 'Water-soaked streaks; yellowing',
     'cultural_controls': 'Resistant varieties; clean seed; balanced fertilization; sanitation',
     'chemical_control': 'Copper-based bactericides (copper oxychloride)',
     'brands': 'Copper oxychloride products',
     'notes': 'Protective spray only'},
    {'crop': 'rice', 'name': 'Rice Hispa', 'type': 'Insect pest',
     'symptoms': 'White-scraped streaks on leaves',
     'cultural_controls': 'Timely planting; resistant varieties; conserve predators',
     'chemical_control': 'Chlorpyrifos/pyrethroids (check registration)',
     'brands': 'Local pyrethroid products e.g., Karate',
     'notes': 'Integrated measures preferred'},
    {'crop': 'rice', 'name': 'Brown Spot', 'type': 'Fungal disease',
     'symptoms': 'Brown lesions on leaves/grains; poor seedling vigor',
     'cultural_controls': 'Balanced fertilization (silicon helps); well-drained nurseries; seed treatment',
     'chemical_control': 'Mancozeb; carbendazim; triazoles',
     'brands': 'Dithane; Bavistin',
     'notes': 'Healthy seedlings reduce incidence'},
    {'crop': 'rice', 'name': 'False Smut', 'type': 'Fungal disease',
     'symptoms': 'Greenish/yellowish spore balls on grains',
     'cultural_controls': 'Balanced N; sanitation; avoid excess N at panicle initiation',
     'chemical_control': 'Propiconazole; azoxystrobin mixes',
     'brands': 'Amistar Top; Tilt',
     'notes': 'Avoid eating contaminated grains; follow PHI'},
    {'crop': 'rice', 'name': 'Leaf Scald', 'type': 'Fungal disease',
     'symptoms': 'Elongated gray lesions with brown margin',
     'cultural_controls': 'Resistant varieties; rotation; balanced nutrition',
     'chemical_control': 'Triazoles; mancozeb',
     'brands': 'Tilt; Dithane',
     'notes': 'Treat early infection stages'},
    {'crop': 'rice', 'name': 'Leaf Smud', 'type': 'Fungal disease',
     'symptoms': 'Black smudgy patches',
     'cultural_controls': 'Manage humidity; balanced nutrition; disease-free seed',
     'chemical_control': 'Mancozeb; propiconazole',
     'brands': 'Dithane; Tilt',
     'notes': 'Mostly cosmetic; integrated measures'},
    {'crop': 'rice', 'name': 'Sheath Blight', 'type': 'Fungal disease',
     'symptoms': 'Lesions on sheath near water line; blighting',
     'cultural_controls': 'Reduce plant density; balanced N; clean seed; biological controls (Trichoderma)',
     'chemical_control': 'Azoxystrobin + difenoconazole; propiconazole',
     'brands': 'Amistar Top; Tilt',
     'notes': 'Avoid excessive N and dense canopies'},
    {'crop': 'rice', 'name': 'Narrow Brown Leaf Spot', 'type': 'Fungal disease',
     'symptoms': 'Narrow brown lesions along veins',
     'cultural_controls': 'Field sanitation; spray if severe',
     'chemical_control': 'Cercospora-targeting fungicides (mancozeb; triazoles)',
     'brands': 'Dithane; Tilt',
     'notes': 'Monitor and spray at threshold'},
    {'crop': 'rice', 'name': 'Sheath Rot', 'type': 'Fungal disease',
     'symptoms': 'Sheath discoloration around panicle; unfilled grains',
     'cultural_controls': 'Healthy seed; balanced nutrition; remove infected panicles',
     'chemical_control': 'Propiconazole and other systemics',
     'brands': 'Tilt and other triazoles',
     'notes': 'Integrated approach; check labels'},
    {'crop': 'rice', 'name': 'Rice Blast', 'type': 'Fungal disease',
     'symptoms': 'Diamond-shaped lesions; neck and panicle blast',
     'cultural_controls': 'Resistant varieties; balanced N; spray at first sign',
     'chemical_control': 'Triazoles (propiconazole); strobilurins (azoxystrobin)',
     'brands': 'Tilt; Amistar Top',
     'notes': 'Major disease — monitor closely'},
    {'crop': 'rice', 'name': 'Tungro', 'type': 'Viral disease (vector-transmitted)',
     'symptoms': 'Yellowing; stunting; reduced tillering',
     'cultural_controls': 'Resistant varieties; control leafhopper vectors; virus-free seedlings',
     'chemical_control': 'Vector control: thiamethoxam; imidacloprid',
     'brands': 'Actara; Confidor',
     'notes': 'No direct cure; prevention essential'},

    # Cotton
    {'crop': 'cotton', 'name': 'Aphids', 'type': 'Insect pest',
     'symptoms': 'Leaf curling; honeydew; sooty mold',
     'cultural_controls': 'Conserve predators (ladybirds); avoid excess N; reflective mulches',
     'chemical_control': 'Imidacloprid; thiamethoxam; pyrethroids for heavy infestations',
     'brands': 'Confidor; Actara; Karate',
     'notes': 'Use thresholds; avoid killing predators'},
    {'crop': 'cotton', 'name': 'Army worm', 'type': 'Insect pest',
     'symptoms': 'Defoliation by caterpillars',
     'cultural_controls': 'Handpicking on small farms; conserve parasitoids; biopesticides (Bt/spinosad)',
     'chemical_control': 'Spinosad; Bt formulations; pyrethroids',
     'brands': 'Spinosad products; Bt formulations',
     'notes': 'Use pheromone/light traps for monitoring'},
    {'crop': 'cotton', 'name': 'Bacterial blight', 'type': 'Bacterial disease',
     'symptoms': 'Angular leaf spots; water-soaked lesions on bolls',
     'cultural_controls': 'Resistant varieties; seed treatment; crop rotation; avoid overhead irrigation',
     'chemical_control': 'Copper-based bactericides for foliar protection',
     'brands': 'Copper oxychloride products',
     'notes': 'Follow label; integrate with cultural controls'},
    {'crop': 'cotton', 'name': 'Boll rot', 'type': 'Fungal/bacterial complex',
     'symptoms': 'Rotting of bolls; discolored lint',
     'cultural_controls': 'Avoid insect damage; balanced irrigation; timely picking',
     'chemical_control': 'Fungicide on bolls not always effective; manage insects and harvest timing',
     'brands': 'Products to manage insect vectors and protect bolls',
     'notes': 'Control causes (insects; waterlogging)'},
    {'crop': 'cotton', 'name': 'Curl virus (Cotton Leaf Curl Virus)', 'type': 'Viral disease',
     'symptoms': 'Leaf curling; vein thickening; stunting; reduced bolls',
     'cultural_controls': 'Resistant varieties; control whitefly; rogue infected plants',
     'chemical_control': 'Control vectors: imidacloprid; thiamethoxam; IGRs',
     'brands': 'Confidor; Actara; sticky traps; neem oils',
     'notes': 'No chemical cure; vector control essential'},
    {'crop': 'cotton', 'name': 'Fusarium wilt', 'type': 'Fungal disease',
     'symptoms': 'Yellowing; wilting; vascular discoloration',
     'cultural_controls': 'Resistant cultivars; rotation; soil solarization; seed treatment',
     'chemical_control': 'Seed treatment (carbendazim); soil fumigation impractical',
     'brands': 'Bavistin (Carbendazim)',
     'notes': 'Use certified seed; sanitation'},
    {'crop': 'cotton', 'name': 'Green cotton boll', 'type': 'Physiological/immature',
     'symptoms': 'Bolls remain green and do not open',
     'cultural_controls': 'Adequate potassium; proper irrigation scheduling; avoid late N',
     'chemical_control': 'No pesticide; manage nutrition and water',
     'brands': '—',
     'notes': 'Not a disease — physiological'},
    {'crop': 'cotton', 'name': 'Powdery mildew', 'type': 'Fungal disease',
     'symptoms': 'White powdery patches on leaves',
     'cultural_controls': 'Resistant varieties; spacing; sulfur; remove affected leaves',
     'chemical_control': 'Sulfur; propiconazole',
     'brands': 'Sulfur formulations; Tilt',
     'notes': 'Prefer cultural measures; sulfur effective'},
    {'crop': 'cotton', 'name': 'Target spot', 'type': 'Fungal disease',
     'symptoms': 'Circular spots with concentric rings on leaves and bolls',
     'cultural_controls': 'Rotation; remove crop debris; spray if severe',
     'chemical_control': 'Triazoles; mancozeb; azoxystrobin mixes',
     'brands': 'Tilt; Dithane; Amistar Top',
     'notes': 'Integrated approach recommended'},
]


def seed_guidance_if_needed():
    db = SessionLocal()
    try:
        for item in SEED_DATA:
            existing = db.query(DiseaseGuidance).filter(
                DiseaseGuidance.crop == item['crop'].lower(),
                DiseaseGuidance.name == item['name']
            ).first()
            if existing:
                continue
            row = DiseaseGuidance(
                guidance_id=str(uuid.uuid4()),
                crop=item['crop'].lower(),
                name=item['name'],
                type=item['type'],
                symptoms=item.get('symptoms'),
                cultural_controls=item.get('cultural_controls'),
                chemical_control=item.get('chemical_control'),
                brands=item.get('brands'),
                notes=item.get('notes'),
            )
            db.add(row)
        db.commit()
    finally:
        db.close()


