artifact_location: file:C:/Users/WALEED TRADERS/OneDrive/Desktop/AgriSmart/runs/mlflow/494585220760827455
creation_time: 1778600397732
experiment_id: '494585220760827455'
last_update_time: 1778600397732
lifecycle_stage: active
name: C:\Users\WALEED TRADERS\OneDrive\Desktop\AgriSmart\runs\yolo_train
trace_location: null
workspace: default
