apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: agrismart
spec:
  type: ClusterIP
  selector:
    app: yolo-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
